version: '3.8'

services:
  # FastAPI
  fastapi:
    build: .
    command: uvicorn main:app --reload
    volumes:
      - ./:/app
    depends_on:
      - redis
      - mongodb

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/fastapi.conf
    depends_on:
      - fastapi
